### ISSUE TITLE
Converting recursive types to json schemas allows throws recursion errors

### ISSUE THREAD

**Issue by kevinand11** [ts-oas/ts-oas#4]
type Recursive = {
    value: Recursive | number
}

Whenever TypescriptOAS.getSchemas() is run over a recursive type like the one above, it throws this error
 function getMergedSymbol(symbol) {
                            ^

RangeError: Maximum call stack size exceeded
    at getMergedSymbol (/node_modules/typescript/lib/typescript.js:48530:29)
    at getParentOfSymbol (/typescript/lib/typescript.js:48541:14)
    at getAliasForSymbolInContainer (/typescript/lib/typescript.js:48654:25)
    at /typescript.js:48635:52
    at mapDefined (/typescript.js:374:24)
    at getContainersOfSymbol (/typescript.js:48635:14)
    at getSymbolChain (/typescript.js:50549:29)
    at lookupSymbolChainWorker (/typescript.js:50534:38)
    at lookupSymbolChain (/typescript.js:50528:16)
    at symbolToTypeNode (/typescript.js:50704:23)

**Comment by alireza-mf** [comment]
Thanks for your feedback. Fixed in [v0.4.2](https://github.com/ts-oas/ts-oas/commit/e83504f303b2c2007eaa90f61f0cf0f2a08115cb).
